apiVersion: v1
kind: Pod
metadata:
  name: nettest
spec:
  # nodeName needs to be set to the name of a node where gcfs-csi-driver.exe has been started manually.
  # It can be omitted if the driver is running on all Windows nodes in the cluster.
  nodeName: <cluster-windows-node-name>
  containers:
   - name: nettest
     image: e2eteam/nettest:1.0
     volumeMounts:
       - mountPath: C:\SMBShare
         name: pvfs
  volumes:
   - name: pvfs
     persistentVolumeClaim:
       claimName: pvc-filestore