# TODO: Pass secrets in a different way.
# See https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: smb-secret
type: Opaque
stringData:
  # smbUser and smbPassword need to be updated.
  smbUser: <smb-share-address>\smbuser
  smbPassword: <smb-share-password-for-smbuser>
